version: '3'
services:
  postgres:
    healthcheck:
      test: pg_isready -U ${DB_USER}
      interval: 5s 
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - proxy
    ports:
      - 5432:5432
    image: docker.io/postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

networks:
  proxy:
