[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
anyhow = "1.0.75"
chrono = "0.4.31"
dotenv = "0.15.0"
reqwest = { version = "0.11.22", features = ["blocking"] }
url = "2.4.1"
