name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**/README.md"
      - "esp/**"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    working-directory: proxy

jobs:
  rust-checks:
    name: Rust Checks (Proxy)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: build
            args: --release
          - command: fmt
            args: --all -- --check --color always
          - command: clippy
            args: --all-targets --all-features --workspace -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1 
        with: 
          toolchain: stable
          override: true 
          components: rustfmt, clippy
      - name: Run command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
